//! JobExecutor: a background `std::thread` that processes pending tiles one at
//! a time by spawning child `arnis` processes.
//!
//! The executor never blocks the async runtime — it lives entirely on a stdlib
//! thread and communicates with the axum web server via:
//!   * `Arc<Mutex<JobManifest>>` for state reads (status endpoints, UI grid).
//!   * `Arc<JobControl>` for pause/cancel signals (atomic flags).
//!   * `tokio::sync::broadcast::Sender<ExecutorEvent>` for live UI updates.
//!
//! Pause/cancel semantics: the executor only checks the control flags **between
//! tiles**, never mid-tile. This guarantees the world is always in a consistent
//! state when the executor stops.
//!
//! Memory containment: each tile is generated by spawning a child `arnis`
//! process with the tile's bbox and a per-tile output directory. When the
//! child exits, the OS reclaims every byte it allocated — there is no
//! per-tile leakage in the parent.

use std::collections::VecDeque;
use std::path::PathBuf;
use std::process::Command;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};
use std::time::Instant;

use serde::Serialize;
use tokio::sync::broadcast;

use super::manifest::{unix_now, JobManifest, JobStatus, TileStatus};

/// Atomic control flags shared between the web server and the executor.
#[derive(Debug, Default)]
pub struct JobControl {
    pub pause: AtomicBool,
    pub cancel: AtomicBool,
}

impl JobControl {
    pub fn new() -> Arc<Self> {
        Arc::new(Self::default())
    }

    pub fn request_pause(&self) {
        self.pause.store(true, Ordering::SeqCst);
    }
    pub fn clear_pause(&self) {
        self.pause.store(false, Ordering::SeqCst);
    }
    pub fn request_cancel(&self) {
        self.cancel.store(true, Ordering::SeqCst);
    }
    pub fn is_paused(&self) -> bool {
        self.pause.load(Ordering::SeqCst)
    }
    pub fn is_canceled(&self) -> bool {
        self.cancel.load(Ordering::SeqCst)
    }
}

/// Real-time events emitted to the WebSocket clients and to the in-memory
/// log ring buffer.
#[derive(Clone, Debug, Serialize)]
#[serde(tag = "type", content = "data", rename_all = "snake_case")]
pub enum ExecutorEvent {
    JobStarted {
        job_id: String,
        total: usize,
    },
    TileStart {
        tile_id: String,
        index: usize,
    },
    TileDone {
        tile_id: String,
        index: usize,
        duration_secs: u64,
    },
    TileFailed {
        tile_id: String,
        index: usize,
        error: String,
    },
    JobPaused,
    #[allow(dead_code)]
    JobResumed,
    JobDone {
        done: usize,
        failed: usize,
        canceled: usize,
    },
    JobCanceled,
    LogLine {
        line: String,
    },
}

/// Thread-safe ring buffer of recent log lines. Capped at 300 lines; older
/// entries are evicted FIFO so the memory footprint stays bounded.
#[derive(Debug, Default)]
pub struct LogBuffer {
    inner: Mutex<VecDeque<String>>,
}

impl LogBuffer {
    pub fn new() -> Arc<Self> {
        Arc::new(Self::default())
    }

    pub fn push(&self, line: String) {
        let mut g = self.inner.lock().unwrap();
        if g.len() >= 300 {
            g.pop_front();
        }
        g.push_back(line);
    }

    pub fn snapshot(&self) -> Vec<String> {
        self.inner.lock().unwrap().iter().cloned().collect()
    }

    #[allow(dead_code)]
    pub fn clear(&self) {
        self.inner.lock().unwrap().clear();
    }
}

pub struct JobExecutor {
    pub manifest: Arc<Mutex<JobManifest>>,
    pub control: Arc<JobControl>,
    pub events: broadcast::Sender<ExecutorEvent>,
    pub logs: Arc<LogBuffer>,
}

impl JobExecutor {
    pub fn new(
        manifest: Arc<Mutex<JobManifest>>,
        control: Arc<JobControl>,
        events: broadcast::Sender<ExecutorEvent>,
        logs: Arc<LogBuffer>,
    ) -> Self {
        Self {
            manifest,
            control,
            events,
            logs,
        }
    }

    /// Spawn the executor on its own OS thread and run until the job is done,
    /// paused, or canceled. The returned `JoinHandle` is detached by the
    /// caller; it can also be `.join()`ed in tests.
    pub fn spawn(self) -> std::thread::JoinHandle<()> {
        std::thread::Builder::new()
            .name("arnis-tile-executor".into())
            .spawn(move || self.run())
            .expect("spawn executor thread")
    }

    fn run(self) {
        // Mark job as running.
        {
            let mut m = self.manifest.lock().unwrap();
            if m.status == JobStatus::Done || m.status == JobStatus::Canceled {
                return;
            }
            m.status = JobStatus::Running;
            m.touch();
            let _ = m.save_atomic();
            let _ = self.events.send(ExecutorEvent::JobStarted {
                job_id: m.job_id.clone(),
                total: m.total,
            });
        }

        loop {
            // Check pause/cancel between tiles only.
            if self.control.is_canceled() {
                self.finalize_canceled();
                return;
            }
            if self.control.is_paused() {
                self.mark_paused();
                return;
            }

            // Snapshot the next-pending index + a clone of the tile entry, then
            // release the manifest lock before doing any I/O.
            let work = {
                let mut m = self.manifest.lock().unwrap();
                match m.next_pending() {
                    None => None,
                    Some(idx) => {
                        m.tiles[idx].status = TileStatus::Running;
                        m.tiles[idx].started_at = Some(unix_now());
                        m.tiles[idx].error = None;
                        m.touch();
                        let _ = m.save_atomic();
                        Some((idx, m.tiles[idx].clone()))
                    }
                }
            };
            let Some((idx, entry)) = work else {
                self.finalize_done();
                return;
            };

            let _ = self.events.send(ExecutorEvent::TileStart {
                tile_id: entry.task.id.clone(),
                index: idx,
            });
            self.log(format!(
                "[tile {}] starting (row={}, col={}, bbox={:?})",
                entry.task.id, entry.task.row, entry.task.col, entry.task.bbox
            ));

            let started = Instant::now();
            let result = self.run_one_tile(&entry.tile_dir, &entry);
            let duration = started.elapsed().as_secs();

            let mut m = self.manifest.lock().unwrap();
            match result {
                Ok(()) => {
                    m.tiles[idx].status = TileStatus::Done;
                    m.tiles[idx].finished_at = Some(unix_now());
                    m.recount();
                    m.touch();
                    let _ = m.save_atomic();
                    drop(m);
                    let _ = self.events.send(ExecutorEvent::TileDone {
                        tile_id: entry.task.id.clone(),
                        index: idx,
                        duration_secs: duration,
                    });
                    self.log(format!("[tile {}] done in {duration}s", entry.task.id));
                }
                Err(e) => {
                    m.tiles[idx].status = TileStatus::Failed;
                    m.tiles[idx].finished_at = Some(unix_now());
                    m.tiles[idx].error = Some(e.clone());
                    m.recount();
                    m.touch();
                    let _ = m.save_atomic();
                    drop(m);
                    let _ = self.events.send(ExecutorEvent::TileFailed {
                        tile_id: entry.task.id.clone(),
                        index: idx,
                        error: e.clone(),
                    });
                    self.log(format!("[tile {}] FAILED: {e}", entry.task.id));
                }
            }
        }
    }

    fn finalize_done(&self) {
        let mut m = self.manifest.lock().unwrap();
        m.recount();
        // If there are still pending tiles (shouldn't happen here but be safe)
        // leave the job in its current state; otherwise mark Done.
        if m.next_pending().is_none() {
            m.status = if m.failed > 0 && m.done == 0 {
                JobStatus::Failed
            } else {
                JobStatus::Done
            };
        }
        m.touch();
        let _ = m.save_atomic();
        let _ = self.events.send(ExecutorEvent::JobDone {
            done: m.done,
            failed: m.failed,
            canceled: m.canceled,
        });
        self.log(format!(
            "[job {}] complete — done={}, failed={}, canceled={}",
            m.job_id, m.done, m.failed, m.canceled
        ));
    }

    fn finalize_canceled(&self) {
        let mut m = self.manifest.lock().unwrap();
        for t in m.tiles.iter_mut() {
            if t.status == TileStatus::Pending || t.status == TileStatus::Running {
                t.status = TileStatus::Canceled;
            }
        }
        m.recount();
        m.status = JobStatus::Canceled;
        m.touch();
        let _ = m.save_atomic();
        let _ = self.events.send(ExecutorEvent::JobCanceled);
        self.log(format!("[job {}] canceled", m.job_id));
    }

    fn mark_paused(&self) {
        let mut m = self.manifest.lock().unwrap();
        m.status = JobStatus::Paused;
        m.touch();
        let _ = m.save_atomic();
        let _ = self.events.send(ExecutorEvent::JobPaused);
        self.log(format!("[job {}] paused", m.job_id));
    }

    fn log(&self, line: String) {
        self.logs.push(line.clone());
        let _ = self.events.send(ExecutorEvent::LogLine { line });
    }

    /// Spawn a child `arnis` process to generate this single tile into its own
    /// per-tile output directory. Stdout/stderr are inherited so the child's
    /// progress lines stream directly through the parent terminal — the log
    /// panel still gets summary lines via `self.log(..)`.
    fn run_one_tile(
        &self,
        tile_dir: &PathBuf,
        entry: &super::manifest::TileEntry,
    ) -> Result<(), String> {
        std::fs::create_dir_all(tile_dir).map_err(|e| format!("create tile dir failed: {e}"))?;

        let exe = std::env::current_exe().map_err(|e| format!("can't resolve current exe: {e}"))?;

        let settings = self.manifest.lock().unwrap().settings.clone();

        let mut cmd = Command::new(&exe);
        cmd.arg("--bbox")
            .arg(entry.task.buffered_bbox.to_arnis_arg())
            .arg("--output-dir")
            .arg(tile_dir);

        cmd.arg("--scale").arg(format!("{}", settings.scale));
        if settings.terrain {
            cmd.arg("--terrain");
        }
        cmd.arg(format!("--interior={}", settings.interior));
        cmd.arg(format!("--roof={}", settings.roof));
        if settings.fillground {
            cmd.arg("--fillground");
        }
        cmd.arg(format!("--land-cover={}", settings.land_cover));
        if settings.bedrock {
            cmd.arg("--bedrock");
        }

        // Tag the child so it never falls into GUI mode (more than 1 arg
        // already prevents that, but be explicit).
        cmd.env("ARNIS_TILE_CHILD", "1");

        let status = cmd
            .status()
            .map_err(|e| format!("failed to spawn child: {e}"))?;
        if !status.success() {
            return Err(format!(
                "child exited with status {}",
                status
                    .code()
                    .map(|c| c.to_string())
                    .unwrap_or_else(|| "<signal>".to_string())
            ));
        }
        Ok(())
    }
}
