//! JobExecutor: a background `std::thread` that processes pending tiles one at
//! a time by spawning child `arnis` processes.
//!
//! The executor never blocks the async runtime — it lives entirely on a stdlib
//! thread and communicates with the axum web server via:
//!   * `Arc<Mutex<JobManifest>>` for state reads (status endpoints, UI grid).
//!   * `Arc<JobControl>` for pause/cancel signals (atomic flags).
//!   * `tokio::sync::broadcast::Sender<ExecutorEvent>` for live UI updates.
//!
//! Pause/cancel semantics: the executor only checks the control flags **between
//! tiles**, never mid-tile. This guarantees the world is always in a consistent
//! state when the executor stops.
//!
//! Memory containment: each tile is generated by spawning a child `arnis`
//! process with the tile's bbox and a per-tile output directory. When the
//! child exits, the OS reclaims every byte it allocated — there is no
//! per-tile leakage in the parent.

use std::collections::VecDeque;
use std::path::PathBuf;
use std::process::{Command, Stdio};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant};

use serde::Serialize;
use tokio::sync::broadcast;

use super::manifest::{unix_now, JobManifest, JobStatus, TileStatus};

/// Atomic control flags shared between the web server and the executor.
#[derive(Debug, Default)]
pub struct JobControl {
    pub pause: AtomicBool,
    pub cancel: AtomicBool,
}

impl JobControl {
    pub fn new() -> Arc<Self> {
        Arc::new(Self::default())
    }

    pub fn request_pause(&self) {
        self.pause.store(true, Ordering::SeqCst);
    }
    pub fn clear_pause(&self) {
        self.pause.store(false, Ordering::SeqCst);
    }
    pub fn request_cancel(&self) {
        self.cancel.store(true, Ordering::SeqCst);
    }
    pub fn is_paused(&self) -> bool {
        self.pause.load(Ordering::SeqCst)
    }
    pub fn is_canceled(&self) -> bool {
        self.cancel.load(Ordering::SeqCst)
    }
}

/// Real-time events emitted to the WebSocket clients and to the in-memory
/// log ring buffer.
#[derive(Clone, Debug, Serialize)]
#[serde(tag = "type", content = "data", rename_all = "snake_case")]
pub enum ExecutorEvent {
    JobStarted {
        job_id: String,
        total: usize,
    },
    TileStart {
        tile_id: String,
        index: usize,
    },
    TileDone {
        tile_id: String,
        index: usize,
        duration_secs: u64,
    },
    TileFailed {
        tile_id: String,
        index: usize,
        error: String,
    },
    TileSkipped {
        tile_id: String,
        index: usize,
        reason: String,
    },
    JobPaused,
    #[allow(dead_code)]
    JobResumed,
    JobDone {
        done: usize,
        skipped: usize,
        failed: usize,
        canceled: usize,
    },
    JobCanceled,
    LogLine {
        line: String,
    },
}

/// Thread-safe ring buffer of recent log lines. Capped at 300 lines; older
/// entries are evicted FIFO so the memory footprint stays bounded.
#[derive(Debug, Default)]
pub struct LogBuffer {
    inner: Mutex<VecDeque<String>>,
}

impl LogBuffer {
    pub fn new() -> Arc<Self> {
        Arc::new(Self::default())
    }

    pub fn push(&self, line: String) {
        let mut g = self.inner.lock().unwrap();
        if g.len() >= 300 {
            g.pop_front();
        }
        g.push_back(line);
    }

    pub fn snapshot(&self) -> Vec<String> {
        self.inner.lock().unwrap().iter().cloned().collect()
    }

    #[allow(dead_code)]
    pub fn clear(&self) {
        self.inner.lock().unwrap().clear();
    }
}

/// Outcome of generating a single tile. `Done` means the child wrote the
/// tile world; `Skipped` means the area contained no OSM data and was not
/// worth running through the full generator (typically open ocean).
enum TileOutcome {
    Done,
    Skipped(String),
}

pub struct JobExecutor {
    pub manifest: Arc<Mutex<JobManifest>>,
    pub control: Arc<JobControl>,
    pub events: broadcast::Sender<ExecutorEvent>,
    pub logs: Arc<LogBuffer>,
    /// When the manifest was last persisted. Used to throttle disk writes —
    /// for huge jobs (whole-Earth = ~76k tiles), serializing the full manifest
    /// after every tile would write tens of GB.
    last_save: Mutex<Instant>,
}

/// Minimum interval between manifest writes when nothing else forces a save.
/// State transitions (start/pause/cancel/done) always force an immediate save.
const SAVE_THROTTLE: Duration = Duration::from_millis(2500);

impl JobExecutor {
    pub fn new(
        manifest: Arc<Mutex<JobManifest>>,
        control: Arc<JobControl>,
        events: broadcast::Sender<ExecutorEvent>,
        logs: Arc<LogBuffer>,
    ) -> Self {
        Self {
            manifest,
            control,
            events,
            logs,
            last_save: Mutex::new(Instant::now() - SAVE_THROTTLE * 2),
        }
    }

    /// Persist the manifest if enough time has elapsed since the last save
    /// (or `force` is true). Always touches `updated_at`.
    fn maybe_save(&self, m: &mut JobManifest, force: bool) {
        m.touch();
        let mut last = self.last_save.lock().unwrap();
        if force || last.elapsed() >= SAVE_THROTTLE {
            let _ = m.save_atomic();
            *last = Instant::now();
        }
    }

    /// Spawn the executor on its own OS thread and run until the job is done,
    /// paused, or canceled. The returned `JoinHandle` is detached by the
    /// caller; it can also be `.join()`ed in tests.
    pub fn spawn(self) -> std::thread::JoinHandle<()> {
        std::thread::Builder::new()
            .name("arnis-tile-executor".into())
            .spawn(move || self.run())
            .expect("spawn executor thread")
    }

    fn run(self) {
        // Mark job as running.
        {
            let mut m = self.manifest.lock().unwrap();
            if m.status == JobStatus::Done || m.status == JobStatus::Canceled {
                return;
            }
            m.status = JobStatus::Running;
            self.maybe_save(&mut m, true);
            let _ = self.events.send(ExecutorEvent::JobStarted {
                job_id: m.job_id.clone(),
                total: m.total,
            });
        }

        loop {
            // Check pause/cancel between tiles only.
            if self.control.is_canceled() {
                self.finalize_canceled();
                return;
            }
            if self.control.is_paused() {
                self.mark_paused();
                return;
            }

            // Snapshot the next-pending index + a clone of the tile entry, then
            // release the manifest lock before doing any I/O.
            let work = {
                let mut m = self.manifest.lock().unwrap();
                match m.next_pending() {
                    None => None,
                    Some(idx) => {
                        m.tiles[idx].status = TileStatus::Running;
                        m.tiles[idx].started_at = Some(unix_now());
                        m.tiles[idx].error = None;
                        self.maybe_save(&mut m, false);
                        Some((idx, m.tiles[idx].clone()))
                    }
                }
            };
            let Some((idx, entry)) = work else {
                self.finalize_done();
                return;
            };

            let _ = self.events.send(ExecutorEvent::TileStart {
                tile_id: entry.task.id.clone(),
                index: idx,
            });
            self.log(format!(
                "[tile {}] starting (row={}, col={}, bbox={:?})",
                entry.task.id, entry.task.row, entry.task.col, entry.task.bbox
            ));

            let started = Instant::now();
            // Cheap pre-flight Overpass probe: skip the costly child spawn
            // entirely if the tile clearly contains no OSM data. This is what
            // turns a whole-Earth job from "76k child processes" into "a few
            // hundred where land actually is".
            let mut result = match probe_tile_has_data(&entry.task.buffered_bbox) {
                Some(false) => Ok(TileOutcome::Skipped("empty Overpass probe".to_string())),
                _ => self.run_one_tile(&entry.tile_dir, &entry),
            };

            // If the child finished cleanly, merge its per-tile world into
            // the master world directory so the user can open it in
            // Minecraft and see one continuous world covering all completed
            // tiles. Merge errors demote the tile to Failed so they show up
            // in the UI.
            if matches!(result, Ok(TileOutcome::Done)) {
                let master_world_dir = self.manifest.lock().unwrap().world_path.clone();
                match super::merge::find_child_world_dir(&entry.tile_dir) {
                    Some(child_world) => {
                        match super::merge::merge_tile_into_master(
                            &child_world,
                            &master_world_dir,
                        ) {
                            Ok(n) => {
                                self.log(format!(
                                    "[tile {}] merged {n} chunks into master world",
                                    entry.task.id
                                ));
                                // After a successful merge the per-tile dir
                                // is redundant and just eats disk; remove it.
                                let _ = std::fs::remove_dir_all(&entry.tile_dir);
                            }
                            Err(e) => {
                                result = Err(format!("merge failed: {e}"));
                            }
                        }
                    }
                    None => {
                        result = Err("child produced no world dir to merge".to_string());
                    }
                }
            }

            let duration = started.elapsed().as_secs();

            let mut m = self.manifest.lock().unwrap();
            match result {
                Ok(TileOutcome::Done) => {
                    m.tiles[idx].status = TileStatus::Done;
                    m.tiles[idx].finished_at = Some(unix_now());
                    m.recount();
                    self.maybe_save(&mut m, false);
                    drop(m);
                    let _ = self.events.send(ExecutorEvent::TileDone {
                        tile_id: entry.task.id.clone(),
                        index: idx,
                        duration_secs: duration,
                    });
                    self.log(format!("[tile {}] done in {duration}s", entry.task.id));
                }
                Ok(TileOutcome::Skipped(reason)) => {
                    m.tiles[idx].status = TileStatus::Skipped;
                    m.tiles[idx].finished_at = Some(unix_now());
                    m.recount();
                    self.maybe_save(&mut m, false);
                    drop(m);
                    let _ = self.events.send(ExecutorEvent::TileSkipped {
                        tile_id: entry.task.id.clone(),
                        index: idx,
                        reason: reason.clone(),
                    });
                    self.log(format!("[tile {}] skipped ({reason})", entry.task.id));
                }
                Err(e) => {
                    m.tiles[idx].status = TileStatus::Failed;
                    m.tiles[idx].finished_at = Some(unix_now());
                    m.tiles[idx].error = Some(e.clone());
                    m.recount();
                    self.maybe_save(&mut m, false);
                    drop(m);
                    let _ = self.events.send(ExecutorEvent::TileFailed {
                        tile_id: entry.task.id.clone(),
                        index: idx,
                        error: e.clone(),
                    });
                    self.log(format!("[tile {}] FAILED: {e}", entry.task.id));
                }
            }
        }
    }

    fn finalize_done(&self) {
        let mut m = self.manifest.lock().unwrap();
        m.recount();
        if m.next_pending().is_none() {
            m.status = if m.failed > 0 && m.done == 0 && m.skipped == 0 {
                JobStatus::Failed
            } else {
                JobStatus::Done
            };
        }
        self.maybe_save(&mut m, true);
        let _ = self.events.send(ExecutorEvent::JobDone {
            done: m.done,
            skipped: m.skipped,
            failed: m.failed,
            canceled: m.canceled,
        });
        self.log(format!(
            "[job {}] complete — done={}, skipped={}, failed={}, canceled={}",
            m.job_id, m.done, m.skipped, m.failed, m.canceled
        ));
    }

    fn finalize_canceled(&self) {
        let mut m = self.manifest.lock().unwrap();
        for t in m.tiles.iter_mut() {
            if t.status == TileStatus::Pending || t.status == TileStatus::Running {
                t.status = TileStatus::Canceled;
            }
        }
        m.recount();
        m.status = JobStatus::Canceled;
        self.maybe_save(&mut m, true);
        let _ = self.events.send(ExecutorEvent::JobCanceled);
        self.log(format!("[job {}] canceled", m.job_id));
    }

    fn mark_paused(&self) {
        let mut m = self.manifest.lock().unwrap();
        m.status = JobStatus::Paused;
        self.maybe_save(&mut m, true);
        let _ = self.events.send(ExecutorEvent::JobPaused);
        self.log(format!("[job {}] paused", m.job_id));
    }

    fn log(&self, line: String) {
        self.logs.push(line.clone());
        let _ = self.events.send(ExecutorEvent::LogLine { line });
    }

    /// Spawn a child `arnis` process to generate this single tile into its own
    /// per-tile output directory. Stdout/stderr are inherited so the child's
    /// progress lines stream directly through the parent terminal — the log
    /// panel still gets summary lines via `self.log(..)`.
    fn run_one_tile(
        &self,
        tile_dir: &PathBuf,
        entry: &super::manifest::TileEntry,
    ) -> Result<TileOutcome, String> {
        std::fs::create_dir_all(tile_dir).map_err(|e| format!("create tile dir failed: {e}"))?;

        let exe = std::env::current_exe().map_err(|e| format!("can't resolve current exe: {e}"))?;

        let settings = self.manifest.lock().unwrap().settings.clone();

        let mut cmd = Command::new(&exe);
        cmd.arg("--bbox")
            .arg(entry.task.buffered_bbox.to_arnis_arg())
            .arg("--output-dir")
            .arg(tile_dir);

        cmd.arg("--scale").arg(format!("{}", settings.scale));
        if settings.terrain {
            cmd.arg("--terrain");
        }
        cmd.arg(format!("--interior={}", settings.interior));
        cmd.arg(format!("--roof={}", settings.roof));
        if settings.fillground {
            cmd.arg("--fillground");
        }
        cmd.arg(format!("--land-cover={}", settings.land_cover));
        if settings.bedrock {
            cmd.arg("--bedrock");
        }

        cmd.env("ARNIS_TILE_CHILD", "1");
        cmd.stdout(Stdio::piped()).stderr(Stdio::piped());

        let output = cmd
            .output()
            .map_err(|e| format!("failed to spawn child: {e}"))?;

        let combined = format!(
            "{}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );

        // Heuristic: detect tiles that are empty (open ocean / Antarctica /
        // no OSM coverage). The arnis CLI reports either "API returned no
        // data" or panics with an explicit empty-bbox message; both should
        // count as Skipped, not Failed, so the dashboard stays meaningful
        // when generating large regions.
        let looks_empty = [
            "API returned no data",
            "no data",
            "empty bounding box",
            "Bbox doesn't include any element",
            "called `Option::unwrap()` on a `None` value",
        ]
        .iter()
        .any(|needle| combined.contains(needle));

        if !output.status.success() {
            if looks_empty {
                return Ok(TileOutcome::Skipped("no OSM data".to_string()));
            }
            // Surface the last meaningful line of stderr in the error message
            // so the UI shows something better than "exit 101".
            let last_line = combined
                .lines()
                .rev()
                .find(|l| !l.trim().is_empty())
                .unwrap_or("")
                .trim()
                .to_string();
            return Err(format!(
                "child exited with status {}: {}",
                output
                    .status
                    .code()
                    .map(|c| c.to_string())
                    .unwrap_or_else(|| "<signal>".to_string()),
                last_line
            ));
        }

        if looks_empty {
            return Ok(TileOutcome::Skipped("no OSM data".to_string()));
        }
        Ok(TileOutcome::Done)
    }
}

/// Lightweight Overpass probe: ask for the count of nodes/ways/relations
/// inside the bbox with a tight timeout, and return whether any element
/// exists. Used to skip generating empty (e.g. open ocean) tiles without
/// paying the full child-process startup cost. Returns `None` if we couldn't
/// reach Overpass (we then fall back to running the child).
fn probe_tile_has_data(bbox: &super::grid::BBox) -> Option<bool> {
    let q = format!(
        "[out:json][timeout:8];(node({},{},{},{});way({},{},{},{});relation({},{},{},{}););out count;",
        bbox.min_lat, bbox.min_lng, bbox.max_lat, bbox.max_lng,
        bbox.min_lat, bbox.min_lng, bbox.max_lat, bbox.max_lng,
        bbox.min_lat, bbox.min_lng, bbox.max_lat, bbox.max_lng,
    );
    let endpoints = [
        "https://overpass-api.de/api/interpreter",
        "https://z.overpass-api.de/api/interpreter",
    ];
    let client = reqwest::blocking::Client::builder()
        .timeout(Duration::from_secs(10))
        .build()
        .ok()?;
    for url in endpoints {
        let resp = client.post(url).body(q.clone()).send();
        let Ok(r) = resp else { continue };
        if !r.status().is_success() {
            continue;
        }
        let Ok(text) = r.text() else { continue };
        // Overpass "out count" returns JSON with elements[0].tags.{nodes,ways,relations,total}.
        // We don't bother fully deserializing — substring-search the keys.
        let total_pos = text.find("\"total\"")?;
        let after = &text[total_pos..];
        // Find the first ":" then the first digit run.
        let colon = after.find(':')?;
        let mut count: u64 = 0;
        let mut started = false;
        for ch in after[colon + 1..].chars() {
            if ch.is_ascii_digit() {
                started = true;
                count = count * 10 + (ch as u64 - '0' as u64);
            } else if started {
                break;
            }
        }
        return Some(count > 0);
    }
    None
}
